server:
  port: ${WEB-SERVER-PORT:6210} #Порт веб-сервера
  http2:
    enabled: true
  undertow:
    max-http-post-size: ${SERVER-MAX-HTTP-POST-SIZE:15MB} #Максимальный объем тела запроса, поддерживаемый веб-сервером

spring:
  application:
    name: notes-service
    admin:
      admin-block-option-on: ${ADMIN-BLOCK-OPTION-ON:true}
    client:
      using-default-client-id: ${USING-DEFAULT-CLIENT-ID:true}
  servlet:
    multipart:
      max-file-size: ${MAX-SERVLET-MULTIPART-FILE-SIZE:15MB} #Максимальный объем Multipart файла
      max-request-size: ${MAX-SERVLET-MULTIPART-REQUEST-SIZE:15MB} #Максимальный объем запроса, содержащего Multipart
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${HIBERNATE-DDL-HANDLING:none} #Генерация сущностей на основе классов. Рекомендуется использовать значения none (если нет необходимости в изменении схемы) и create-drop (для сброса схемы после запуска; используется как первый шаг для автоматических изменений схемы)
    open-in-view: false
  datasource:
    url: jdbc:postgresql://${DB-SERVER-HOST:localhost}:${DB-SERVER-PORT:6200}/${DB-NAME:uni_notes_db} #URL БД сервиса
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      driver-class-name: org.postgresql.Driver
      username: ${DB-USER:root} #Имя пользователя к УЗ сервиса в БД
      password: ${DB-PASSWORD:123} #Пароль к УЗ сервиса в БД
      maximum-pool-size: ${DB-MAXIMUM-POOL-SIZE:10} #Максимальное количество соединений в пуле HikariCP
      transaction-isolation: ${DB-TRANSACTION-ISOLATION:TRANSACTION_REPEATABLE_READ} #Уровень изоляции транзакций БД
      auto-commit: ${DB-AUTO-COMMIT:true} #Режим работы с подключением к БД, в котором каждая операция выполняется в отдельной транзакции
      connection-timeout: ${DB-CONNECTION-TIMEOUT:500000} #Таймаут соединений HikariCP в миллисекундах
      idle-timeout: ${DB-CONNECTION-IDLE-TIMEOUT:300000} #Время жизни неактивных соединений в пуле HikariCP в миллисекундах
      max-lifetime: ${DB-CONNECTION-MAX-LIFETIME:900000} #Время жизни соединений в пуле HikariCP в миллисекундах
      minimum-idle: ${DB-POOL-MINIMUM-IDLE-CONNECTIONS:2} #Минимальное количество свободных подключений, которые пул HikariCP будет всегда поддерживать
      schema: schema
    continue-on-error: false
    initialization-mode: always
  sql:
    init:
      mode: ${DB-INIT-MODE:never} # Режим автоматического запуска DDL-скрипта БД. Возможные значения: always, never, embedded
      continue-on-error: false
      encoding: UTF-8
  security:
    access-token-ttl: ${ACCESS-TOKEN-TTL:60} #Время жизни access-токена в минутах
    refresh-token-ttl: ${REFRESH-TOKEN-TTL:24} #Время жизни refresh-токена в часах
  jackson:
    default-property-inclusion: non_null
  devtools:
    restart:
      enabled: ${DEVTOOLS-RESTART-ENABLED:false} #Активация devtools независимо от загрузчика классов
    add-properties: ${DEVTOOLS-ADD-PROPERTIES:false} #Применение параметров режима разработчика по умолчанию
  cache:
    cache-names: NoteCache, NoteByNoteIdAndUserIdCache, NoteObjectCache, CurrentUserCache, UserByEmailCache, UserByUsernameCache, CategoryCache, CategoryByIdAndUserIdCache, TagCache, TagByIdAndUserIdCache, MediaMetadata
    type: caffeine
    caffeine:
      spec: maximumSize = ${MAXIMUM-CACHE-SIZE:500}, expireAfterAccess=${CACHE-EXPIRE-AFTER-ACCESS:300}s #Максимальная вместимость кэша в записях; Время хранения кэша после последнего доступа в секундах

grpc:
  client:
    note-data-modifying.address: static://${GRPC-NOTE-DATA-MODIFYING-SERVICE-HOST:localhost}:${GRPC-NOTE-DATA-MODIFYING-SERVICE-PORT:6213}
    note-data-modifying.negotiation-type: plaintext
    note-search.address: static://${GRPC-NOTE-SEARCH-SERVICE-HOST:localhost}:${GRPC-NOTE-SEARCH-SERVICE-PORT:6214}
    note-search.negotiation-type: plaintext
    grpc-api-token-service.address: static://${GRPC-API-TOKEN-SERVICE-HOST:localhost}:${GRPC-API-TOKEN-SERVICE-PORT:6214}
    grpc-api-token-service.negotiation-type: plaintext
  server:
    port: ${GRPC-SERVER-PORT:6216}
    max-inbound-message-size: ${MAX-INBOUND-MESSAGE-SIZE:2MB}
    security:
      enabled: false

jwt:
  access-token-key: '{"kty":"oct","k":"hi7S5RX5ZRZooHA0RKGctZ-KtR9FoESgCnH-3BNg5XI"}'
  refresh-token-key: '{"kty":"oct","k":"956PBFst1FguLr5irJD-aQ"}'

s3:
  bucket: ${S3-BUCKET:notes-resources} #Наименование бакета S3
  endpoint-url: ${S3-ENDPOINT-URL:https://hb.ru-msk.vkcloud-storage.ru} #url для доступа к S3
  key-id: ${S3-KEY-ID:kHrtrTZdg8v6cHtrCGouYT} #Перед запуском добавить ID ключа #ID ключа доступа к УЗ S3
  key: ${S3-KEY:84wc1ekar6G8umte797m2TDmC9FB311oBi6oaxeEX6cm} #Перед запуском добавить ключ #Ключ доступа к УЗ S3
  region-name: ${S3-REGION-NAME:ru-msk} #Базовый регион S3

resources:
  max-note-tag-ids-filter-for-search-amount: ${MAX-NOTE-TAG-IDS-FILTER-FOR-SEARCH-AMOUNT:10} #Максимальное количество ID тегов, которые можно указать при поиске/получении заметок в query-параметрах запроса
  max-users-categories-amount: ${MAX-NOTES-CATEGORIES-AMOUNT:25} #Максимальное количество категорий для пользователя
  max-note-image-file-size: ${MAX-NOTE-IMAGE-FILE-SIZE:15} #Максимальный размер фото к заметке в Мб
  max-note-text-file-size: ${MAX-NOTE-TEXT-FILE-SIZE:1} #Максимальный размер текстового файла заметки в Мб
  max-note-images-amount: ${MAX-NOTE-IMAGES-AMOUNT:5} #Максимальное количество приложенных к заметке фото


logging:
  level:
    org.springframework.security.web: DEBUG
    root: ${DEFAULT-LOGGING-LEVEL:DEBUG} #Уровень логирования сервиса. Возможные значения: ERROR / WARN / INFO / DEBUG / TRACE

debug:
  ${DEBUG:false} #Переключатель режима отладки сервиса. Возможные значения: true (режим отладки) / false (обычный режим)

flk:
  active: Flk10000001, Flk10000002, Flk10000003, Flk10000004, Flk10000005, Flk10000006, Flk10000007, Flk10000008, Flk10000009, Flk10000010, Flk10000011, Flk10000012, Flk10000013, Flk10000014, Flk10000015, Flk10000016, Flk10000017, Flk10000018, Flk10000019, Flk10000020, Flk10000021, Flk10000022, Flk10000023, Flk10000024  #Список активных ФЛК. Указанные номера должны соответствовать существующим в директории классов ФЛК